apiVersion: v1
kind: Service # this means wanna create service 
metadata:
  creationTimestamp: null
  labels:
    app: ashus1
  name: ashus1 # name of service 
spec:
  ports:
  - name: 1234-80
    port: 1234 # service port number 
    protocol: TCP
    targetPort: 80 # pod application port 
  selector:  # this is pod finder using label of POD 
    run: geethapod2 # this is label  of your pod/pods where you wanna forward traffic 
  type: NodePort  # type of service 
status:
  loadBalancer: {}
