apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of POD 
    run: ashupod123 # key & value -- run is key and ashupod123 is value 
  name: ashupod123 # name of the POD 
spec:
  containers:
  - image: dockerashu/ashuciscowebapp:v001 # image from docker hub 
    name: ashupod123 # name of container 
    ports: # application port 
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
