apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webui
  name: webui
  namespace: ashuns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webui
    spec:
      nodeName: ip-172-31-70-124.ec2.internal # minion 1 host 
      volumes:
      - name: ashuvolx # volume to be creatd 
        hostPath:
         path: /var/run/docker.sock # docker unix socket of Minion 1
         type: Socket 
      containers:
      - image: portainer/portainer:latest
        name: portainer
        volumeMounts:
        - name: ashuvolx
          mountPath: /var/run/docker.sock 
        resources: {}
status: {}
