apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupodx1
  name: ashupodx1
spec:
  containers:
  - image: alpine
    name: ashupodx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
